= DMIT2015 Course Project - Full Stack Development Research

== OBJECTIVE
Upon completion of this assignment, you will have demonstrated the ability to:

- Research, implement, and present a REST API backend application using a backend stack that has not been used in the course.
- Research, implement, and present a REST Client frontend application using a frontend stack that has not been used in the course.

== PROBLEM DESCRIPTION
In this course we have been using Jakarta EE platform and Eclipse Microservices to build full stack applications.
In the course project you will explore and present other platform/framworks you could use the build the backend and the frontend of a full stack application. 
The dataset you will be using will be the same dataset (EdmontonPropertyAssessmentData) from assignment 8.

The backend application can be implemented using any one of the following backend frameworks:

* https://spring.io/projects/spring-boot[Spring Boot], https://quarkus.io/[Quarkus], https://helidon.io/[Helidon], https://micronaut.io/[Micronaut] (Java programming language)
* ASP.NET Core (C# programming language)
* Express.js (Javascript programming language)
* Laravel, CakePHP (PHP programming language)
* Django, Flask (Python programming language)

The backend application must implement a REST API with the following endpoints:

* An endpoint to find a single EdmontonPropertyAssessmentData by House Number, Street Name, and Suite.
* An endpoint to find a list of EdmontonPropertyAssessmentData by Neighhourhood, Minimum Assessed Value, and Maximum Assessed Value.
* An endpoint to return a JWT for database or LDAP account.
* An endpoint to create a EdmontonPropertyAssessmentData using a JWT.
* An endpoint to update a EdmontonPropertyAssessmentData using a JWT.

The frontend of a full stack application could be implemented using any one of following frontend frameworks:

* React, Angular, Vue.js (Javascript programming language)
* ASP.NET Core Razor Pages, ASP.NET Core Blazor (C# programming language)
* Native mobile app
* PHP (PHP programming language)

The frontend application must implement the following pages:

* A page to find a single EdmontonPropertyAssessmentData by House Number, Street Name, and Suite.
* A page to find a list of EdmontonPropertyAssessmentData by Neighhourhood, Minimum Assessed Value, and Maximum Assessed Value.
* A page to login and store the JWT returned for future usage.
* A secured page to create a EdmontonPropertyAssessmentData using a JWT.
* A secured page to find, edit, and update a EdmontonPropertyAssessmentData using a JWT.

== GIT REPOSITORY SETUP
. Login to Moodle and navigate to the link to create a private github repository for this assignment.
. Click on *Accept this assignment* to allow github to create a private github repository for you.
. Wait for the *You are ready to go!* messaage then click on the link to navigate to your assignment repository
. Click on *Clone or download* button then copy the URL to your repository to the clipboard.
. Put all the projects you created for this assignment in this repository.


== REQUIREMENTS for REST client frontend application
. Research and complete an guide/tutorial on a frontend framework that shows you how to access an REST API to perform CRUD functionality.
. Using the completed guide project as a reference, create another project using the same frontend framework to access the REST API from your assignment 8 backend project or from the backproject of this assignment.
. Write a tutorial in the `README.md` file or create a video tutorial on the steps and code to fetch data from a REST API and to post data to a REST API.

== REQUIREMENTS for REST services backend application
. Research and complete an guide/tutorial on a backend framework that shows you how to create REST API endpoints to perform CRUD operations and queries on a database.
. Using the completed guide project as a reference, create another project using the same backend framework to create REST API endpoints to perform CRUD operations and write queries using the dataset from assignemnt 8.
. Write a tutorial in the `README.md` file or create video tutorials on the steps and code:
.. Perform CRUD operations and write queries on the dataset for EdmontonPropertyAssessmentData.
.. Create REST API endpoints to perform CRUD operations and execute queries on the dataset for EdmontonPropertyAssessmentData.
.. To authenticate an database or LDAP user and return a JWT for the authenticated user.
.. Restrict access to REST API endpoints by role name.
.. To logout or revoke a JWT token


== MARKING GUIDE

[cols="4,1"]
|===
| Requirement | Marks

a| REST Client frontend application 

* (1 mark) Present the guide you completed, its features, and highlight key concepts you learned from it.
* (2 marks) Present the steps and code in your tutorial on how to fetch data from a REST API and display the returned content to the page.
* (2 marks) Present the steps and code in your tutorial on how to post data to a REST API
* (1 mark) Demonstrate the process and the code to login and logout.
* (1 mark) Demonstrate the page to find a single EdmontonPropertyAssessmentData by House Number, Street Name, and Suite.
* (1 mark) Demonstrate the page to find a list of EdmontonPropertyAssessmentData by Neighourhood and Assessed Value range.
* (1 mark) Demonstrate the secure page to create EdmontonPropertyAssessmentData.
* (1 mark) Demonstrate the secure page to edit/update EdmontonPropertyAssessmentData.

|10

a| REST API endpoints backend application

* (1 mark) Present the guide you completed, its features, and highlight key concepts you learned from it.
* (2 marks) Present your tutorial on how to perform CRUD operations and write queries using the backend framework you have chosen.
* (2 marks) Present your tutorial on how to create REST API endpoints to perform CRUD operations using the backend framework you have chosen.
* (2 marks) Present your tutorial on how authenticate an database/ldap user and return a JWT using the backend framework you have chosen.
* (1 mark) Present your tutorial on how to restrict access to REST API endpoints using the backend framework you have chosen.
* (1 mark) Present your tutorial on how to logout and revoke an JWT token using the backend framework you have chosen.
* (1 mark) Demonstrate using Http Request or Postman that you REST API endpoints are working as expected.

|10


|===

== SUBMISSION/PRESENTATION/DEMONSTRATION REQUIREMENTS
* Commit and push your project to your git repository before the due date.
* Present your project to your class on the due date.

== Resources
* https://spring.io/guides[Spring Guides]
* https://quarkus.io/guides/[Quarkus Guides]
* https://helidon.io/docs/v3/#/mp/guides/overview[Helidon Guides]
* https://guides.micronaut.io/latest/index.html[Micronaut Guides]